In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [3]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])

In [7]:
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
MATRIX = torch.tensor([[7,8],
                      [0,0]])
MATRIX

tensor([[7, 8],
        [0, 0]])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 6]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0][2][1]

tensor(5)

In [28]:
#Random Tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9668, 0.6714, 0.9618, 0.1400],
        [0.8123, 0.6977, 0.2000, 0.1343],
        [0.5791, 0.4079, 0.9940, 0.5416]])

In [30]:
#Random tensor with similar shape to an image tensor
random_tensor_new = torch.rand(size=(224,224,3)) #height, width, color channel
random_tensor_new.shape, random_tensor_new.ndim

(torch.Size([224, 224, 3]), 3)

In [33]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [35]:
zero_to_ten = torch.arange(0,10,1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
ten_ones = torch.ones_like(zero_to_ten)
ten_zeros = torch.zeros_like(zero_to_ten)
ten_ones, ten_zeros

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [46]:
float_32_tensor = torch.tensor([3.0,2.0,9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [47]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0314, 0.1416, 0.3750, 0.8991],
        [0.5334, 0.2648, 0.7969, 0.7950],
        [0.9759, 0.8309, 0.1384, 0.0839]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [63]:
sample = torch.arange(1,20,2)
sample = torch.add(sample, 10)
sample

tensor([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [64]:
sample = torch.mul(sample, 10)
sample

tensor([110, 130, 150, 170, 190, 210, 230, 250, 270, 290])

In [65]:
sample = torch.sub(sample, 10)
sample

tensor([100, 120, 140, 160, 180, 200, 220, 240, 260, 280])

In [66]:
sample = torch.div(sample, 10)
sample

tensor([10., 12., 14., 16., 18., 20., 22., 24., 26., 28.])

In [67]:
sample = sample * sample
sample

tensor([100., 144., 196., 256., 324., 400., 484., 576., 676., 784.])

In [74]:
sample = torch.tensor([1,2,3])
torch.matmul(sample, sample)
# sample@sample

tensor(14)

In [82]:
sample1 = torch.rand(3,4)
sample2 = torch.rand(3,4)
torch.matmul(sample1,sample2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [83]:
sample2 = sample2.T
res = torch.mm(sample1, sample2)
res.shape, res

(torch.Size([3, 3]),
 tensor([[0.7408, 1.0977, 1.1701],
         [1.4099, 1.4405, 1.4507],
         [0.6823, 0.7511, 0.7010]]))

In [88]:
# Matrix multiplication and dot products in linear nn
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=3,
                        out_features=6)

x=sample2
output = linear(x)
x.shape, output, output.shape

(torch.Size([4, 3]),
 tensor([[-0.0825,  0.2868,  0.1128,  0.0922,  0.0581,  0.5815],
         [ 0.3139,  0.5973, -0.1735, -0.1598,  0.2801,  0.5597],
         [ 0.3125,  0.5641,  0.0937,  0.0107,  0.3510,  0.6792],
         [ 0.2277,  0.3539,  0.3062,  0.2718,  0.2321,  0.8008]],
        grad_fn=<AddmmBackward0>),
 torch.Size([4, 6]))

In [104]:
#Aggregations 
x = torch.arange(0,100,10)
print(f"Max: {x.max()}")
print(f"Min: {x.min()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")
       

Max: 90
Min: 0
Mean: 45.0
Sum: 450


In [105]:
#Positional min/max
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [114]:
#Reshaping, stacking, squeezing and unsqueezing¶
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [116]:
x_reshaped = x.reshape(2,4)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [117]:
z = x.view(4,2)
z, z.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]),
 torch.Size([4, 2]))

In [119]:
z[:, 0] =5
z,x

(tensor([[5., 2.],
         [5., 4.],
         [5., 6.],
         [5., 8.]]),
 tensor([5., 2., 5., 4., 5., 6., 5., 8.]))

In [123]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 5., 4., 5., 6., 5., 8.],
         [5., 2., 5., 4., 5., 6., 5., 8.],
         [5., 2., 5., 4., 5., 6., 5., 8.],
         [5., 2., 5., 4., 5., 6., 5., 8.]]),
 torch.Size([4, 8]))

In [129]:
x_reshaped = x.reshape(1,8)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 5., 4., 5., 6., 5., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([5., 2., 5., 4., 5., 6., 5., 8.])
New shape: torch.Size([8])


In [133]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 5., 4., 5., 6., 5., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[5., 2., 5., 4., 5., 6., 5., 8.]])
New shape: torch.Size([1, 8])


In [139]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = torch.permute(x_original,[2, 0, 1]) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
